[package]
name = "sch-read"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
kicad-sexpr = { path = "../kicad-sexpr" }
sch-model = { path = "../sch-model" }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
