// SPDX-License-Identifier: Apache-2.0
//! opspec v1 schema emission (drift-checked against `tests/conformance/ops.v1.schema.json`)
//! and op-list regressions (docs/engine-conformance.md §4).

use sch_ops::{expand, template, Op, OpList, CORE_OPS, MACRO_OPS, PROTOCOL_VERSION};
use serde_json::{json, Map, Value};
use std::path::PathBuf;

fn sorted(v: Value) -> Value {
    match v {
        Value::Object(m) => {
            let mut b: Vec<(String, Value)> = m.into_iter().map(|(k, v)| (k, sorted(v))).collect();
            b.sort_by(|a, c| a.0.cmp(&c.0));
            Value::Object(b.into_iter().collect::<Map<String, Value>>())
        }
        Value::Array(a) => Value::Array(a.into_iter().map(sorted).collect()),
        other => other,
    }
}

/// The op vocabulary as a JSON document: every op name, its full and required-only field
/// templates, whether it is a macro and whether it is structural. This is what the harness
/// and the docs (`docs/opspec-v1.md`) pin against.
fn schema() -> Value {
    let mut ops = Map::new();
    for (kind, names) in [("core", CORE_OPS), ("macro", MACRO_OPS)] {
        for name in names {
            let full = template(name, false).unwrap_or_else(|| panic!("no template for {name}"));
            let required =
                template(name, true).unwrap_or_else(|| panic!("no required template for {name}"));
            let structural = {
                let list = OpList {
                    protocol_version: PROTOCOL_VERSION,
                    target_format: "kicad".into(),
                    groups: Default::default(),
                    sheets: Default::default(),
                    ops: vec![full.clone()],
                };
                expand(&list)
                    .ok()
                    .map(|e| e.ops.iter().any(|o| o.op.is_structural()))
            };
            ops.insert(
                name.to_string(),
                json!({ "kind": kind, "fields": full, "required": required, "structural": structural }),
            );
        }
    }
    sorted(json!({
        "$comment": "Generated by crates/sch-ops/tests/schema_and_regressions.rs; regenerate with FLUXSMITH_UPDATE_SCHEMA=1 cargo test -p sch-ops. Field names/values are the op templates of opspec v1.",
        "protocol_version": PROTOCOL_VERSION,
        "core_ops": CORE_OPS,
        "macro_ops": MACRO_OPS,
        "ops": ops,
    }))
}

fn schema_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/conformance/ops.v1.schema.json")
}

#[test]
fn ops_v1_schema_matches_checked_in_file() {
    let want = serde_json::to_string_pretty(&schema()).unwrap() + "\n";
    let path = schema_path();
    if std::env::var("FLUXSMITH_UPDATE_SCHEMA")
        .map(|v| v == "1")
        .unwrap_or(false)
    {
        std::fs::write(&path, &want).unwrap();
        return;
    }
    let have = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        have, want,
        "opspec v1 drifted from tests/conformance/ops.v1.schema.json — this is a protocol change: bump/annotate docs/opspec-v1.md and regenerate with FLUXSMITH_UPDATE_SCHEMA=1"
    );
}

fn list(ops: Value) -> OpList {
    OpList::from_value(json!({"protocol_version": 1, "ops": ops})).unwrap()
}

/// reg: 0.18.0 — macro fields were validated only after expansion, so a typo'd field was
/// silently accepted and produced a plausible-looking circuit.
#[test]
fn reg_macro_fields_validated_before_expansion() {
    // required field missing (typo) on a macro: refused with an index pointing at the macro
    let errs = expand(&list(json!([{"op":"place_decoupling","power_nett":"+3V3","x_mil":0,"y_mil":0,"designator":"C1"}]))).unwrap_err();
    assert_eq!(errs[0].index, 0);
    assert!(errs[0].code.starts_with("OPLIST_"), "{errs:?}");
    assert!(
        errs[0].message.contains("power_net"),
        "message names the missing field: {}",
        errs[0].message
    );
    // wrong type on a macro
    let errs = expand(&list(json!([{"op":"place_pullup","net":"SDA","rail_net":"+3V3","x_mil":"zero","y_mil":0,"designator":"R1"}]))).unwrap_err();
    assert_eq!(errs[0].index, 0);
    // too many designators on a macro
    let errs = expand(&list(json!([{"op":"place_divider","x_mil":0,"y_mil":0,"top_net":"A","mid_net":"B","bottom_net":"C","designators":["R1","R2","R3"]}]))).unwrap_err();
    assert!(
        errs.iter()
            .any(|e| e.index == 0 && e.code == "OPLIST_CONSTRAINT"),
        "{errs:?}"
    );
}

/// reg: 0.18.0 — positional `designators` written in the wrong order silently produced a BOM
/// where the resistor was D1 and the LED R3. The expansion must bind by role or refuse.
#[test]
fn reg_macro_designators_bind_by_role_not_position() {
    let swapped = list(
        json!([{"op":"place_led_indicator","x_mil":0,"y_mil":0,"net":"PA5","designators":["D1","R1"],"r_value":"1k"}]),
    );
    match expand(&swapped) {
        Err(errs) => assert!(errs[0].index == 0, "{errs:?}"),
        Ok(ex) => {
            for o in &ex.ops {
                if let Op::PlaceComponent {
                    lib_id, designator, ..
                } = &o.op
                {
                    let prefix: String = designator
                        .chars()
                        .take_while(|c| c.is_ascii_alphabetic())
                        .collect();
                    let expect = if lib_id.starts_with("Device:R") {
                        "R"
                    } else if lib_id.starts_with("Device:LED") {
                        "D"
                    } else {
                        continue;
                    };
                    assert_eq!(
                        prefix, expect,
                        "{lib_id} got designator {designator} (positional swap leaked)"
                    );
                }
            }
        }
    }
}

/// reg: 0.20.0 — `place_gnd`/`place_vcc` failed on standard installs because the symbol
/// source scan ran before the implicit lib_id was injected. Expansion carries the lib_id.
#[test]
fn reg_place_gnd_and_vcc_expand_with_power_lib_ids() {
    let ex = expand(&list(
        json!([{"op":"place_gnd","at":"C1.2"},{"op":"place_vcc","at":"C1.1","net_name":"+3V3"}]),
    ))
    .unwrap();
    let ids: Vec<(String, String)> = ex
        .ops
        .iter()
        .filter_map(|o| match &o.op {
            Op::PlacePowerPort {
                lib_id, net_name, ..
            } => Some((lib_id.clone(), net_name.clone())),
            _ => None,
        })
        .collect();
    assert_eq!(ids.len(), 2);
    assert_eq!(ids[0], ("power:GND".to_string(), "GND".to_string()));
    assert!(ids[1].0.starts_with("power:"), "{ids:?}");
    assert_eq!(ids[1].1, "+3V3");
}

/// Unknown ops and schema errors come back structured with the authored index.
#[test]
fn reg_unknown_op_is_a_structured_error() {
    let errs = expand(&list(json!([{"op":"add_wire","vertices":[[0,0],[100,0]]},{"op":"place_componen","lib_id":"Device:R","designator":"R1","x_mil":0,"y_mil":0}]))).unwrap_err();
    assert_eq!(errs.len(), 1);
    assert_eq!((errs[0].index, errs[0].code.as_str()), (1, "OPLIST_SCHEMA"));
    assert!(OpList::from_json("{\"protocol_version\":1").is_err());
    assert!(OpList::from_json("{\"protocol_version\":1,\"ops\":{}}").is_err());
}

#[test]
fn macro_rail_params_expand_to_power_ports() {
    // Every rail name becomes a power port: a stock name keeps its own glyph, an unknown ground-class
    // name borrows the GND glyph (the Value carries the real net); signals stay labels; the chain's
    // internal node is one wire, not two labels; macro parts are exact (never nudged).
    let l = list(
        serde_json::json!([{"op":"place_rc_filter","x_mil":1000,"y_mil":1000,"in_net":"IN","out_net":"OUT","designators":["R1","C1"],"gnd_net":"GND"}]),
    );
    let ex = sch_ops::expand(&l).unwrap();
    let ports = |ex: &sch_ops::Expanded| -> Vec<(String, String)> {
        ex.ops
            .iter()
            .filter_map(|e| match &e.op {
                sch_ops::Op::PlacePowerPort {
                    lib_id, net_name, ..
                } => Some((lib_id.clone(), net_name.clone())),
                _ => None,
            })
            .collect()
    };
    assert_eq!(
        ports(&ex),
        vec![("power:GND".to_string(), "GND".to_string())]
    );
    let labels = ex
        .ops
        .iter()
        .filter(|e| matches!(e.op, sch_ops::Op::AddNetLabel { .. }))
        .count();
    assert_eq!(labels, 2, "IN and OUT stay labels; the R-C node is a wire");
    assert_eq!(
        ex.ops
            .iter()
            .filter(|e| matches!(e.op, sch_ops::Op::RouteNet { .. }))
            .count(),
        1
    );
    // macro parts are never nudged apart, but they are not "exact": their origin still snaps to the grid
    assert!(ex
        .ops
        .iter()
        .filter(|e| matches!(e.op, sch_ops::Op::PlaceComponent { .. }))
        .all(|e| e.no_nudge && !e.exact));
    let l2 = list(
        serde_json::json!([{"op":"place_rc_filter","x_mil":1000,"y_mil":1000,"in_net":"IN","out_net":"OUT","designators":["R1","C1"],"gnd_net":"AGND_SENSE"}]),
    );
    let ex2 = sch_ops::expand(&l2).unwrap();
    assert_eq!(
        ports(&ex2),
        vec![("power:GND".to_string(), "AGND_SENSE".to_string())]
    );
    // Divider: the mid node is one labelled wire, rails on both ends are ports (VIN borrows VCC).
    let l3 = list(
        serde_json::json!([{"op":"place_divider","x_mil":1000,"y_mil":1000,"top_net":"VIN","mid_net":"VSENSE","bottom_net":"GND","designators":["R1","R2"],"values":["100k","27k"]}]),
    );
    let ex3 = sch_ops::expand(&l3).unwrap();
    assert_eq!(
        ports(&ex3),
        vec![
            ("power:VCC".to_string(), "VIN".to_string()),
            ("power:GND".to_string(), "GND".to_string())
        ]
    );
    assert!(ex3
        .ops
        .iter()
        .any(|e| matches!(&e.op, sch_ops::Op::RouteNet { label: Some(l), .. } if l == "VSENSE")));
    // A spacing below 500 mil would put the mid label on a body: clamped to 500.
    let l4 = list(
        serde_json::json!([{"op":"place_divider","x_mil":1000,"y_mil":1000,"top_net":"VBUS","mid_net":"VSENSE","bottom_net":"GND","designators":["R1","R2"],"values":["1k","1k"],"spacing_mil":400}]),
    );
    let ex4 = sch_ops::expand(&l4).unwrap();
    let ys: Vec<i64> = ex4
        .ops
        .iter()
        .filter_map(|e| match &e.op {
            sch_ops::Op::PlaceComponent {
                place: sch_ops::Place::At(p),
                ..
            } => Some(p.y),
            _ => None,
        })
        .collect();
    assert_eq!(ys[1] - ys[0], sch_model::mil_to_nm(500.0));
    assert_eq!(sch_ops::power_glyph("-7V"), "VEE");
    assert_eq!(sch_ops::power_glyph("-5V"), "-5V");
    assert_eq!(sch_ops::power_glyph("PGND"), "GND");
    assert_eq!(sch_ops::power_glyph("+3V3"), "+3V3");
}

#[test]
fn known_power_symbols_exist_in_the_stock_library() {
    // The list must never name a symbol KiCad does not ship (the apply would be refused with
    // SYMBOL_NOT_FOUND). Checked against the installed library when one is present.
    let candidates = [
        "/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols/power.kicad_sym",
        "/usr/share/kicad/symbols/power.kicad_sym",
        "C:/Program Files/KiCad/10.0/share/kicad/symbols/power.kicad_sym",
    ];
    let Some(text) = candidates
        .iter()
        .find_map(|p| std::fs::read_to_string(p).ok())
    else {
        eprintln!("no stock power library found; skipping");
        return;
    };
    let missing: Vec<&str> = sch_ops::KNOWN_POWER_SYMBOLS
        .iter()
        .copied()
        .filter(|n| !text.contains(&format!("(symbol \"{n}\"")))
        .collect();
    assert!(missing.is_empty(), "not in power.kicad_sym: {missing:?}");
}

/// opspec v1 has one label op: the scope is a field, not a name. `add_global_label` /
/// `add_hier_label` are aliases the harness rewrites (`src/agent/tools/ops.ts`), and the scope the
/// alias states must arrive here as `scope`, because the engine defaults to `local` — a
/// cross-sheet interface authored as `add_hier_label` and normalised without its scope would
/// become a sheet-local label that joins nothing.
#[test]
fn reg_label_scope_is_a_field_and_defaults_to_local() {
    let parse = |op: Value| -> Result<String, Vec<sch_ops::OpError>> {
        let list = OpList::from_value(json!({"protocol_version": PROTOCOL_VERSION, "ops": [op]}))
            .map_err(|e| vec![e])?;
        let mut ex = expand(&list)?;
        match ex.ops.remove(0).op {
            Op::AddNetLabel { scope, .. } => Ok(format!("{scope:?}")),
            other => panic!("not a label op: {other:?}"),
        }
    };
    let at = json!({"op": "add_net_label", "name": "VOUT", "at": "U1.1"});
    assert_eq!(parse(at.clone()).unwrap(), "Local");
    for (scope, want) in [("global", "Global"), ("hierarchical", "Hierarchical")] {
        let mut op = at.clone();
        op["scope"] = json!(scope);
        assert_eq!(parse(op).unwrap(), want);
    }
    // Nothing else is a scope: a misspelling is refused, never silently local (the harness
    // normalises `hier` to `hierarchical` before the engine sees it).
    let mut bad = at;
    bad["scope"] = json!("hier");
    let err = parse(bad).expect_err("`hier` must not parse as a scope");
    assert_eq!(err[0].code, "OPLIST_CONSTRAINT");
    // `add_global_label` / `add_hier_label` are not ops of the vocabulary.
    for n in ["add_global_label", "add_hier_label"] {
        assert!(!CORE_OPS.contains(&n) && !MACRO_OPS.contains(&n), "{n}");
    }
}

/// `place_array` terminates each element's pins: `pinN_labels` one net per element (alias
/// `pinN_nets`), `pinN_rail` the same rail on all of them as a power port. Before this the macro
/// took neither and a real model's `pin1_labels` / `pin2_rail` were dropped without a word, so
/// every pin of the array floated.
#[test]
fn reg_place_array_wires_each_element() {
    let ex = expand(&list(json!([{
        "op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 4,
        "x_mil": 3000, "y_mil": 3000, "pitch_mil": 400, "direction": "right", "value": "10k",
        "pin1_labels": ["IN0", "IN1", "IN2", "IN3"], "pin2_rail": "GND"
    }])))
    .unwrap();
    assert!(ex.warnings.is_empty(), "{:?}", ex.warnings);
    // 4 x (component, label on pin 1, power port on pin 2), in element order.
    assert_eq!(ex.ops.len(), 12);
    assert_eq!(ex.mapping, vec![(0..12).collect::<Vec<_>>()]);
    for (k, chunk) in ex.ops.chunks(3).enumerate() {
        match &chunk[0].op {
            Op::PlaceComponent { designator, .. } => assert_eq!(*designator, format!("R{}", k + 1)),
            other => panic!("{other:?}"),
        }
        match &chunk[1].op {
            Op::AddNetLabel {
                name, at, scope, ..
            } => {
                assert_eq!(*name, format!("IN{k}"));
                assert_eq!(*scope, sch_ops::Scope::Local);
                assert_eq!(
                    *at,
                    sch_ops::Anchor::Endpoint(sch_ops::Endpoint::Pin {
                        reference: format!("R{}", k + 1),
                        unit: None,
                        pin: "1".into()
                    })
                );
            }
            other => panic!("{other:?}"),
        }
        match &chunk[2].op {
            Op::PlacePowerPort {
                lib_id, net_name, ..
            } => {
                assert_eq!(lib_id, "power:GND");
                assert_eq!(net_name, "GND");
            }
            other => panic!("{other:?}"),
        }
        // Macro parts and their terminations are designed geometry: never nudged apart.
        assert!(chunk.iter().all(|o| o.no_nudge));
    }
    // `pin1_nets` is the same field; `pin2_labels` works on the other pin; an explicit scope keeps
    // a rail-looking name a label of that scope instead of a power port.
    let ex = expand(&list(json!([{
        "op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 2,
        "x_mil": 0, "y_mil": 0, "pin1_rail": "+3V3", "pin2_nets": ["A", "B"], "pin2_scope": "global"
    }])))
    .unwrap();
    assert_eq!(ex.ops.len(), 6);
    assert!(
        matches!(&ex.ops[1].op, Op::PlacePowerPort { lib_id, net_name, .. } if lib_id == "power:+3V3" && net_name == "+3V3")
    );
    assert!(
        matches!(&ex.ops[2].op, Op::AddNetLabel { name, scope, .. } if name == "A" && *scope == sch_ops::Scope::Global)
    );
    // A rail name in the label list still becomes a power port (red line 4).
    let ex = expand(&list(json!([{
        "op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 1,
        "x_mil": 0, "y_mil": 0, "pin2_labels": ["GND"]
    }])))
    .unwrap();
    assert!(matches!(&ex.ops[1].op, Op::PlacePowerPort { net_name, .. } if net_name == "GND"));
}

/// A label or a power port sticks out along the pin axis, so a wired array that marches that way
/// is clamped the way the chain macros clamp `spacing_mil`. Across the pins nothing changes.
#[test]
fn place_array_clamps_pitch_only_along_the_pin_axis() {
    let pts = |ex: &sch_ops::Expanded| -> Vec<sch_model::Pt> {
        ex.ops
            .iter()
            .filter_map(|e| match &e.op {
                Op::PlaceComponent {
                    place: sch_ops::Place::At(p),
                    ..
                } => Some(*p),
                _ => None,
            })
            .collect()
    };
    let down = expand(&list(json!([{
        "op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 2,
        "x_mil": 0, "y_mil": 0, "pitch_mil": 400, "direction": "down", "pin2_rail": "GND"
    }])))
    .unwrap();
    let p = pts(&down);
    assert_eq!(p[1].y - p[0].y, sch_model::mil_to_nm(700.0));
    // The same array without wiring keeps the pitch it was given.
    let bare = expand(&list(json!([{
        "op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 2,
        "x_mil": 0, "y_mil": 0, "pitch_mil": 400, "direction": "down"
    }])))
    .unwrap();
    assert_eq!(pts(&bare)[1].y, sch_model::mil_to_nm(400.0));
    // Across the pin axis (the usual row of vertical passives) 400 mil stays 400 mil.
    let right = expand(&list(json!([{
        "op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 2,
        "x_mil": 0, "y_mil": 0, "pitch_mil": 400, "direction": "right", "pin2_rail": "GND"
    }])))
    .unwrap();
    assert_eq!(pts(&right)[1].x, sch_model::mil_to_nm(400.0));
}

/// Lengths are checked against `count`, and the two spellings of the same field are refused
/// together: a half-wired array is worse than a refusal the model can fix.
#[test]
fn place_array_wiring_lengths_are_validated() {
    let base = |extra: Value| {
        let mut o = json!({"op": "place_array", "lib_id": "Device:R", "designator_prefix": "R",
                           "count": 4, "x_mil": 0, "y_mil": 0});
        let m = o.as_object_mut().unwrap();
        for (k, v) in extra.as_object().unwrap() {
            m.insert(k.clone(), v.clone());
        }
        list(json!([o]))
    };
    for (extra, needle) in [
        (
            json!({"pin1_labels": ["A", "B"]}),
            "one net name per element",
        ),
        (json!({"pin1_labels": ["A", "B", "", "D"]}), "is empty"),
        (
            json!({"pin1_labels": ["A", "B", "C", "D"], "pin1_nets": ["A", "B", "C", "D"]}),
            "not both",
        ),
        (
            json!({"pin2_labels": ["A", "B", "C", "D"], "pin2_rail": "GND"}),
            "pin 2 carries one net",
        ),
        (
            json!({"pin1_scope": "sideways"}),
            "local/global/hierarchical",
        ),
    ] {
        let errs = expand(&base(extra.clone())).unwrap_err();
        assert_eq!(errs[0].code, "OPLIST_CONSTRAINT", "{extra} -> {errs:?}");
        assert!(errs[0].message.contains(needle), "{extra} -> {errs:?}");
    }
}

/// reg: a field no branch reads was dropped in silence, so a model that invented `pin1_labels`
/// got an unwired array and no explanation. The parser now reports it as a warning (the op-list
/// still expands), which is what the model needs to correct itself.
#[test]
fn reg_unknown_fields_are_reported_not_swallowed() {
    let ex = expand(&list(json!([
        {"op": "place_array", "lib_id": "Device:R", "designator_prefix": "R", "count": 2,
         "x_mil": 0, "y_mil": 0, "pin1_labels": ["A", "B"], "pin2_raill": "GND", "colour": "red"},
        {"op": "add_junction", "at": [0, 0]}
    ])))
    .unwrap();
    assert_eq!(ex.ops.len(), 5, "the op-list still expands");
    let msgs: Vec<&str> = ex.warnings.iter().map(|w| w.message.as_str()).collect();
    assert_eq!(msgs.len(), 2, "{msgs:?}");
    assert!(ex
        .warnings
        .iter()
        .all(|w| w.index == 0 && w.code == "OPLIST_UNKNOWN_FIELD"));
    // Sorted by field name; each message names the op and lists the fields it does have.
    assert!(msgs[0].starts_with("unknown field `colour` on `place_array` was ignored (known: "));
    assert!(msgs[0].contains("pin1_labels"), "{}", msgs[0]);
    assert!(msgs[1].contains("`pin2_raill`"), "{}", msgs[1]);
    assert!(ex.warnings[1]
        .remediation
        .as_deref()
        .unwrap()
        .contains("ops.template"));
    // The envelope's own fields are never unknown.
    let ex = expand(
        &OpList::from_value(json!({"protocol_version": 1,
        "groups": {"g": {"origin_mil": [0, 0]}}, "sheets": {"p": "p.kicad_sch"},
        "ops": [{"op": "add_junction", "at": [0, 0], "group": "g", "sheet": "p", "note": "n", "exact": true}]}))
        .unwrap(),
    )
    .unwrap();
    assert!(ex.warnings.is_empty(), "{:?}", ex.warnings);
}

/// Guard against the two lists drifting apart: every field of every `template()` must be a field
/// the parser reads, or the unknown-field warning would fire on the engine's own example.
#[test]
fn no_template_field_is_reported_unknown() {
    for op in CORE_OPS.iter().chain(MACRO_OPS.iter()) {
        let l = if *op == "arrange_group" {
            // The template leaves the group name empty; declare it so the op expands.
            OpList::from_value(json!({"protocol_version": 1,
                "groups": {"": {"origin_mil": [0, 0]}},
                "ops": [template(op, false).unwrap()]}))
            .unwrap()
        } else {
            list(json!([template(op, false).unwrap()]))
        };
        if let Ok(ex) = expand(&l) {
            assert!(ex.warnings.is_empty(), "{op}: {:?}", ex.warnings);
        }
    }
}

/// reg: `place_vcc` / `place_gnd` without a `lib_id` drew `power:VCC` for every rail, so a real
/// Build run put four VCC glyphs on a VBUS rail although `power:VBUS` exists. The glyph now
/// follows the net name through the one borrow rule (`power_glyph`), and says so when it borrows.
#[test]
fn reg_rail_port_glyph_follows_the_net_name() {
    let port = |ops: Value| -> (String, String, Vec<String>) {
        let ex = expand(&list(ops)).unwrap();
        let (lib_id, net_name) = ex
            .ops
            .iter()
            .find_map(|e| match &e.op {
                Op::PlacePowerPort {
                    lib_id, net_name, ..
                } => Some((lib_id.clone(), net_name.clone())),
                _ => None,
            })
            .expect("a power port");
        (
            lib_id,
            net_name,
            ex.warnings.iter().map(|w| w.code.clone()).collect(),
        )
    };
    // A stock rail gets its own glyph, silently.
    for (net, glyph) in [
        ("VBUS", "power:VBUS"),
        ("+3V3", "power:+3V3"),
        ("GND", "power:GND"),
        ("VCC", "power:VCC"),
    ] {
        let (lib_id, name, warns) = port(json!([{"op":"place_vcc","at":"C1.1","net_name":net}]));
        assert_eq!((lib_id.as_str(), name.as_str()), (glyph, net));
        assert!(warns.is_empty(), "{net}: {warns:?}");
    }
    // A rail KiCad has no symbol for borrows the nearest glyph and says which one. The Value
    // keeps the real name, which is the name KiCad reads the net from.
    for (net, glyph) in [
        ("USB_5V", "power:+5V"),
        ("MYRAIL", "power:VCC"),
        ("SENSOR_GND", "power:GND"),
        ("-9V_BIAS", "power:-9V"),
    ] {
        let (lib_id, name, warns) = port(json!([{"op":"place_vcc","at":"C1.1","net_name":net}]));
        assert_eq!((lib_id.as_str(), name.as_str()), (glyph, net));
        assert_eq!(
            warns,
            vec!["OPLIST_RAIL_GLYPH_BORROWED".to_string()],
            "{net}"
        );
    }
    // `place_gnd` shares the rule and its own default is silent.
    let (lib_id, name, warns) = port(json!([{"op":"place_gnd","at":"C1.2"}]));
    assert_eq!((lib_id.as_str(), name.as_str()), ("power:GND", "GND"));
    assert!(warns.is_empty(), "{warns:?}");
    // An explicit lib_id still wins.
    let (lib_id, ..) =
        port(json!([{"op":"place_vcc","at":"C1.1","net_name":"VBUS","lib_id":"power:VCC"}]));
    assert_eq!(lib_id, "power:VCC");

    // The borrow itself: a stock rail carried as a whole token, longest first; digits that run
    // into a letter are not a rail name.
    for (rail, glyph) in [
        ("USB_5V", "+5V"),
        ("USB_5VA", "+5VA"),
        ("VDD_3V3", "+3V3"),
        ("3.3V_SENSE", "+3.3V"),
        ("-12V_FAN", "-12V"),
        ("VCC5V", "VCC"),
        ("AUX15V", "VCC"),
        ("MYRAIL", "VCC"),
        ("-7V", "VEE"),
        ("PGND", "GND"),
        ("+3V3", "+3V3"),
    ] {
        assert_eq!(sch_ops::power_glyph(rail), glyph, "glyph for {rail}");
    }
}
